### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SM8Official** [MasterNama17083/UltraMario96Tape-Binary#1]
In Mario 64 hack rom it keeps crashing when I go to into the hole by the red color

**Comment by MasterNama17083** [comment]
> In Mario 64 hack rom it keeps crashing when I go to into the hole by the red color

Is this right?
![image](https://user-images.githubusercontent.com/80534869/176453753-350cd182-8478-459c-abcf-6755e73484f6.png)

**Comment by MasterNama17083** [comment]
It's nothing result crash because entering warp hole it works fine.
![image](https://user-images.githubusercontent.com/80534869/176454360-f59d5054-e572-49ac-a9ba-2eaed538ce0a.png)

**Comment by MasterNama17083** [comment]
@SM8Official What do you think about this?

**Comment by MasterNama17083** [comment]
Won't reply, Closing...

**Comment by MasterNama17083** [comment]
#2 #2 duplicate issues found.
