### ISSUE TITLE
Red carpet by the hole

### ISSUE THREAD

**Issue by CookieJackC** [MasterNama17083/UltraMario96Tape-Binary#2]
Masternama PLS read this,
When I go into the hole by the red carpet the game crashes
I don't know how to go into midnight castle grounds cause of this.
PLS try to help.

**Comment by MasterNama17083** [comment]
Probably caused invalid object (w/ behaviour?) will crash the game it's been two years ago it worked on pc.

I was playing on mobile there's the maze area simply when going to fall down results on crash.


You have already in this issue at #1.
Thanks.

**Comment by CookieJackC** [comment]
Thanks masternama I'll just use a editing app to make my own midnight castle grounds

**Comment by MasterNama17083** [comment]
Btw, I was working on this hack with new generation fresh.
